### ISSUE TITLE
BPMN Diagram not view

### ISSUE THREAD

**Issue by rbajaniya** [FlowzPlatform/workflow#89]
Cannot read property 'length' of undefined

```
getCurrentStatus (log) {
   return (log.length > 0) ? _.head(log).status : ''
}
```

check log variable undefined or not before check length

**Comment by bhumilsarvaiya** [comment]
issue resolved in last commit (https://github.com/FlowzPlatform/workflow/commit/7fdd81b983c91e4677d8154ed4895822c38b2309)
